#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
uname -a | grep "^Darwin" > /dev/null

echo "Starting the ser2net serial port to TCP redirector server..."
echo "Press ^C to shut down the server."
echo "This script will ask for the root password and run ser2net as root because the /dev entries sometimes have restrictive permissions."
if [[ "x$?" == "x0" ]]; then 
    sudo $DIR/ser2net-mac -d -c $DIR/ser2net.conf
else
    sudo ser2net -d -c $DIR/ser2net.conf
fi
