#!/bin/bash
echo "Starting the serial port redirector client..."
echo "Press ^C twice to shut down the server."
while true; do
    socat -d -d -d -t0 -T0 pty,link=/tmp/ttyV0,waitslave tcp:localhost:7000
    echo "~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-"
    echo " Server restarting, press ^C now to exit. "
    echo "~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-"
    sleep 2;
done
