#!/bin/bash
echo "Starting the serial port redirector client..."
echo "Press ^C twice to shut down the server."
while true; do
    sudo socat -d -d -d -t0 -T0 pty,link=/dev/ttyV0,waitslave tcp:localhost:7000
    sleep 1;
done
